/*
 * Copyright (C) 2020 Rajko
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package autopresser.gui;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author Rajko
 */
public class InfoFrame extends javax.swing.JFrame {

    private String defaultKeyboardInfo = "Keyboard status: ";
    private String defaultMouseInfo =    "Mouse status   : ";

    /**
     * Creates new form InfoFrame
     */
    public InfoFrame() {
        System.out.println("Info frame constructed!");
        setUndecorated(true);
        initComponents();
        pack();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        int width = (int) screenSize.getWidth();
        int height = (int) screenSize.getHeight();
        this.setLocation(width - this.getWidth() - 10, height - this.getHeight() - 10);
        this.setAlwaysOnTop(true);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        mouseTextArea = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        keyboardTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mouseTextArea.setEditable(false);
        mouseTextArea.setBackground(new java.awt.Color(255, 255, 0));
        mouseTextArea.setColumns(15);
        mouseTextArea.setRows(3);
        mouseTextArea.setText("Mouse status:     IDLE");
        mouseTextArea.setToolTipText("");
        jScrollPane2.setViewportView(mouseTextArea);

        keyboardTextArea.setEditable(false);
        keyboardTextArea.setBackground(new java.awt.Color(255, 255, 0));
        keyboardTextArea.setColumns(15);
        keyboardTextArea.setRows(3);
        keyboardTextArea.setText("Keyboard status: IDLE");
        keyboardTextArea.setToolTipText("");
        jScrollPane3.setViewportView(keyboardTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void changeKeyboardStatus(String status) {
        keyboardTextArea.setText(defaultKeyboardInfo + status);
    }

    public void changeMouseStatus(String status) {
        mouseTextArea.setText(defaultMouseInfo + status);
    }

    public void changeKeyboardStatusColor(Color color) {
        keyboardTextArea.setBackground(color);
    }
    
    public void setKeyboardStatusIdle() {
         keyboardTextArea.setText(defaultKeyboardInfo + "IDLE");
         changeKeyboardStatusColor(new Color(255, 255, 0));
    }
    
    public void setMouseStatusIdle() {
         mouseTextArea.setText(defaultMouseInfo + "IDLE");
         changeMouseStatusColor(new Color(255, 255, 0));
    }

    public void changeMouseStatusColor(Color color) {
        mouseTextArea.setBackground(color);
    }
    
    public void setKeyboardStatus(String message) {
        keyboardTextArea.setText(message);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea keyboardTextArea;
    private javax.swing.JTextArea mouseTextArea;
    // End of variables declaration//GEN-END:variables

    
}
